[meta]
title = "Django Transcription"
description = "Get started using Deepgram's Transcription with this Django demo app"
author = "Deepgram DX Team <devrel@deepgram.com> (https://developers.deepgram.com)"
repository = "https://github.com/deepgram-starters/django-transcription"
useCase = "STT"
language = "Python"
framework = "Django"
sdk = "5.3.2"

[build]
command = "make init"

[config]
sample = "sample.env"
output = ".env"

[post-build]
message = "Run `make start` to get up and running."
